name: Generate TV Guide 📺

on:
    push:
        branches:
            - master
    schedule:
        - cron: '0 0 * * *'
    workflow_dispatch:

jobs:
    generate:
        runs-on: ubuntu-latest
        timeout-minutes: 120
        container: node:18.18.0-alpine3.18
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: install
              run: |
                apk add --no-cache bash curl
                npm ci
            - name: generate
              run: npm run grab -- --site=tv.blue.ch --lang=de --days=7 --output=dist/guide.xml
            - name: upload artifact
              uses: actions/upload-pages-artifact@v2
              with:
                name: 'github-pages'
                path: 'dist/'
            - name: publish to pages
              uses: actions/deploy-pages@v2
              with:
                artifact_name: 'github-pages'

